theme: jekyll-theme-minimal
logo: images/EOAFRICA-logo.png
title: EOMAJI - an ESA EOAfrica Explorers initiative
# description: Bookmark this to keep an eye on my project updates!
plugins:
  - jekyll-toc
  
related_blog_posts:
  enabled: true
  max_related: 5
