theme: jekyll-theme-minimal
title: EOMAJI - an ESA EOAfrica Explorers initiative
# description: Bookmark this to keep an eye on my project updates!
plugins:
  - jekyll-toc
	
# TOC Settings
toc:
 min_level: 1
 max_level: 3
 list_class: toc
 list_class: toc__list
 sublist_class: toc__sublist
